{"ansible_facts": {"discovered_interpreter_python": "/bin/python3.11"}, "changed": true, "cmd": ["uptime"], "delta": "0:00:00.010432", "end": "2024-12-12 15:42:28.187698", "msg": "", "rc": 0, "start": "2024-12-12 15:42:28.177266", "stderr": "", "stderr_lines": [], "stdout": " 15:42:28 up 3 days, 20:39,  2 users,  load average: 2.23, 2.39, 2.41", "stdout_lines": [" 15:42:28 up 3 days, 20:39,  2 users,  load average: 2.23, 2.39, 2.41"], "warnings": ["Platform linux on host ansible_machine is using the discovered Python interpreter at /bin/python3.11, but future installation of another Python interpreter could change the meaning of that path. See https://docs.ansible.com/ansible-core/2.17/reference_appendices/interpreter_discovery.html for more information."]}