{"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3.10"}, "changed": true, "cmd": ["uptime"], "delta": "0:00:00.016548", "end": "2024-12-12 14:42:28.937505", "msg": "", "rc": 0, "start": "2024-12-12 14:42:28.920957", "stderr": "", "stderr_lines": [], "stdout": " 14:42:28 up 2 days,  6:03,  1 user,  load average: 0.00, 0.02, 0.00", "stdout_lines": [" 14:42:28 up 2 days,  6:03,  1 user,  load average: 0.00, 0.02, 0.00"], "warnings": ["Platform linux on host serverd is using the discovered Python interpreter at /usr/bin/python3.10, but future installation of another Python interpreter could change the meaning of that path. See https://docs.ansible.com/ansible-core/2.17/reference_appendices/interpreter_discovery.html for more information."]}